##### <i>Name:Shabana Mangal<i>
##### <i>Instructer:Dr.Qianyi Cheng<i>
##### <i>Date:3/2/2025<i>
##### <i>Subject:Programming in Chemistry<i>

In [14]:
# Question 1:
import time

def wallis_pi(n):
    product = 1.0
    for i in range(1, n+1):
        product *= (4 * i**2) / (4 * i**2 - 1)
    return 2 * product

# Set the number of iterations for better precision
iterations = 100000

# Start the timer
start_time = time.time()

# Calculate the approximation of pi
approximated_pi = wallis_pi(iterations)

# End the timer
end_time = time.time()

# Print the result and running time
print(f"Approximated Pi: {approximated_pi}")
print(f"Running Time: {end_time - start_time} seconds")


Approximated Pi: 3.141584799657247
Running Time: 0.03185391426086426 seconds


In [13]:
# Question 2:
def fibonacci(n):
    # Initialize the first two terms
    fib_sequence = [0, 1]
    
    # Calculate the Fibonacci terms
    for i in range(2, n):
        next_term = fib_sequence[i-1] + fib_sequence[i-2]
        fib_sequence.append(next_term)
    
    # Return the sequence up to the nth term
    return fib_sequence[:n]

# Example: Display the first 10 terms of the Fibonacci sequence
n = 10
fib_terms = fibonacci(n)

# Print the result
print(f"The first {n} terms of the Fibonacci sequence are: {fib_terms}")


The first 10 terms of the Fibonacci sequence are: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [3]:
# Question 3:
# Atomic numbers
Li, C, Na = 3, 6, 11

# a) Is Li greater than C?
a = Li > C

# b) Is Na less than or equal to C?
b = Na <= C

# c) Is either Li or Na greater than C?
c = Li > C or Na > C

# d) Are both C and Na greater than Li?
d = C > Li and Na > Li

# Print the results
print(f"a) Is Li greater than C? {a}")
print(f"b) Is Na less than or equal to C? {b}")
print(f"c) Is either Li or Na greater than C? {c}")
print(f"d) Are both C and Na greater than Li? {d}")


a) Is Li greater than C? False
b) Is Na less than or equal to C? False
c) Is either Li or Na greater than C? True
d) Are both C and Na greater than Li? True


In [24]:
# Question 4:
def get_opposite_dna_strand(Orignal_Strand):
     # Create Dictionary 
    O_S={"A":"T","T":"A","C":"G","G":"C"}
     # Generate the opposite strand by replacing each base with its pair from the dictionary
    Opposite_Strand="".join(O_S[val] for val in Orignal_Strand)
    return Opposite_Strand
Orignal_Strand="ATGGC"
Opposite_Strand=get_opposite_dna_strand(Orignal_Strand)
print(f"Original DNA strand:{Orignal_Strand}")
print(f"Opposite DNA strand:{Opposite_Strand}")


Original DNA strand:ATGGC
Opposite DNA strand:TACCG


In [25]:
# Question 5:
def rate(A0, k=1.0, n=1):
    ''' (concentration(M), k = 1.0, n = 1) → rate (M/s)
    Takes in the concentration of A (M), the rate constant (k), 
    and the order (n) and returns the rate (M/s)
    '''
    # Apply the differential rate law: Rate = k * [A]^n
    rate_of_reaction = k * (A0 ** n)
    
    return rate_of_reaction


A0 = 0.5 
k = 2.0   
n = 1     

reaction_rate = rate(A0, k, n)
print(f"The rate of the reaction is: {reaction_rate} M/s")


The rate of the reaction is: 1.0 M/s


In [21]:
# Question 6:
import numpy as np
# Step 1: Use np.genfromtxt() to read the atom xyz coordinates
W=np.genfromtxt("/home/Shabana/6780/Files/OtherFiles/Water_Molecule.txt",skip_header=2,usecols=(1,2,3))
W
# Step 2: Define the function to calculate the atom-atom distance
def cal_dis(atom1,atom2):
    return np.sqrt(np.sum((atom1 - atom2) ** 2))
# Step 3: Calculate the atom-atom distances and display the results
O_H1=cal_dis(W[0],W[1])
O_H2=cal_dis(W[0],W[2])    
H1_H2=cal_dis(W[1],W[2])  
O_H1=f"Distance between O and H1: {O_H1} Å"
O_H2=f"Distance between O and H2: {O_H2} Å"
H1_H2=f"Distance between H1 and H2: {H1_H2} Å"
print(O_H1)
print(O_H2)
print(H1_H2)


Distance between O and H1: 0.9690005374652793 Å
Distance between O and H2: 0.9690003348647513 Å
Distance between H1 and H2: 1.52693633514957 Å


In [26]:
# Question 7:
import numpy as np

# Step 1: Generate an array containing integers from 0 to 14 (inclusive)
arr = np.arange(15)

# a) Reshape the array to be a 3x5 array
reshaped_arr = arr.reshape(3, 5)
print("Reshaped array (3x5):")
print(f"\n{reshaped_arr}")

# b) Transpose the array, so now it should be a 5x3 array
transposed_arr = reshaped_arr.T
print("\nTransposed array (5x3):")
print(f"\n{transposed_arr}")

# c) Make the array one-dimensional again without using the reshape() method 

OD_arr=arr.ravel()# returns a view of the original array (if possible) and is memory-efficient.
print("\nReshape array to ID through Ravel:")
print(f"\n{OD_arr}")

# Another Method
# and creates a new 1D array, independent of the original array
flattened_arr = transposed_arr.flatten()
print("\nReshape array to ID through Flatten:")
print(f"\n{flattened_arr}")


Reshaped array (3x5):

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Transposed array (5x3):

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

Reshape array to ID through Ravel:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Reshape array to ID through Flatten:

[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


In [27]:
# Question 8:
import numpy as np

# Generate a 5x3 array with random integers from 0 to 9
arr2 = np.random.randint(0, high=10, size=15).reshape(5, 3)

# Print the array to visualize it
print("Generated Array:")
print(arr2)

# a) Index the second element of the third column (index 1 in column 2)
second_element_third_column = arr2[1, 2]
print(f"\na) Second element of the third column: {second_element_third_column}")

# b) Slice the array to get the entire third row (index 2)
third_row = arr2[2, :]
print(f"\nb) Entire third row: {third_row}")

# c) Slice the array to access the entire first column (index 0)
first_column = arr2[:, 0]
print(f"\nc) Entire first column: {first_column}")

# d) Slice the array to get the last two elements of the first row
last_two_elements_first_row = arr2[0, -2:]
print(f"\nd) Last two elements of the first row: {last_two_elements_first_row}")


Generated Array:
[[2 6 7]
 [5 7 4]
 [1 7 7]
 [6 2 3]
 [6 1 4]]

a) Second element of the third column: 4

b) Entire third row: [1 7 7]

c) Entire first column: [2 5 1 6 6]

d) Last two elements of the first row: [6 7]
